// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: migration.proto

package migration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationPayload_Algorithm int32

const (
	MigrationPayload_ALGORITHM_UNSPECIFIED MigrationPayload_Algorithm = 0
	MigrationPayload_SHA1                  MigrationPayload_Algorithm = 1
	MigrationPayload_SHA256                MigrationPayload_Algorithm = 2
	MigrationPayload_SHA512                MigrationPayload_Algorithm = 3
	MigrationPayload_MD5                   MigrationPayload_Algorithm = 4
)

// Enum value maps for MigrationPayload_Algorithm.
var (
	MigrationPayload_Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "SHA1",
		2: "SHA256",
		3: "SHA512",
		4: "MD5",
	}
	MigrationPayload_Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"SHA1":                  1,
		"SHA256":                2,
		"SHA512":                3,
		"MD5":                   4,
	}
)

func (x MigrationPayload_Algorithm) Enum() *MigrationPayload_Algorithm {
	p := new(MigrationPayload_Algorithm)
	*p = x
	return p
}

func (x MigrationPayload_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPayload_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[0].Descriptor()
}

func (MigrationPayload_Algorithm) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[0]
}

func (x MigrationPayload_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPayload_Algorithm.Descriptor instead.
func (MigrationPayload_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0}
}

type MigrationPayload_DigitCount int32

const (
	MigrationPayload_DIGIT_COUNT_UNSPECIFIED MigrationPayload_DigitCount = 0
	MigrationPayload_SIX                     MigrationPayload_DigitCount = 1
	MigrationPayload_EIGHT                   MigrationPayload_DigitCount = 2
)

// Enum value maps for MigrationPayload_DigitCount.
var (
	MigrationPayload_DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "SIX",
		2: "EIGHT",
	}
	MigrationPayload_DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"SIX":                     1,
		"EIGHT":                   2,
	}
)

func (x MigrationPayload_DigitCount) Enum() *MigrationPayload_DigitCount {
	p := new(MigrationPayload_DigitCount)
	*p = x
	return p
}

func (x MigrationPayload_DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPayload_DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[1].Descriptor()
}

func (MigrationPayload_DigitCount) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[1]
}

func (x MigrationPayload_DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPayload_DigitCount.Descriptor instead.
func (MigrationPayload_DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 1}
}

type MigrationPayload_OtpType int32

const (
	MigrationPayload_OTP_TYPE_UNSPECIFIED MigrationPayload_OtpType = 0
	MigrationPayload_HOTP                 MigrationPayload_OtpType = 1
	MigrationPayload_TOTP                 MigrationPayload_OtpType = 2
)

// Enum value maps for MigrationPayload_OtpType.
var (
	MigrationPayload_OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "HOTP",
		2: "TOTP",
	}
	MigrationPayload_OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"HOTP":                 1,
		"TOTP":                 2,
	}
)

func (x MigrationPayload_OtpType) Enum() *MigrationPayload_OtpType {
	p := new(MigrationPayload_OtpType)
	*p = x
	return p
}

func (x MigrationPayload_OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationPayload_OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[2].Descriptor()
}

func (MigrationPayload_OtpType) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[2]
}

func (x MigrationPayload_OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationPayload_OtpType.Descriptor instead.
func (MigrationPayload_OtpType) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 2}
}

type MigrationPayload struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	OtpParameters []*MigrationPayload_OtpParameters `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	mi := &file_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpParameters() []*MigrationPayload_OtpParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

type MigrationPayload_OtpParameters struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Secret        []byte                      `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                      `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm     MigrationPayload_Algorithm  `protobuf:"varint,4,opt,name=algorithm,proto3,enum=migration.MigrationPayload_Algorithm" json:"algorithm,omitempty"`
	Digits        MigrationPayload_DigitCount `protobuf:"varint,5,opt,name=digits,proto3,enum=migration.MigrationPayload_DigitCount" json:"digits,omitempty"`
	Type          MigrationPayload_OtpType    `protobuf:"varint,6,opt,name=type,proto3,enum=migration.MigrationPayload_OtpType" json:"type,omitempty"`
	Counter       int64                       `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload_OtpParameters) Reset() {
	*x = MigrationPayload_OtpParameters{}
	mi := &file_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload_OtpParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload_OtpParameters) ProtoMessage() {}

func (x *MigrationPayload_OtpParameters) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload_OtpParameters.ProtoReflect.Descriptor instead.
func (*MigrationPayload_OtpParameters) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MigrationPayload_OtpParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *MigrationPayload_OtpParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationPayload_OtpParameters) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *MigrationPayload_OtpParameters) GetAlgorithm() MigrationPayload_Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return MigrationPayload_ALGORITHM_UNSPECIFIED
}

func (x *MigrationPayload_OtpParameters) GetDigits() MigrationPayload_DigitCount {
	if x != nil {
		return x.Digits
	}
	return MigrationPayload_DIGIT_COUNT_UNSPECIFIED
}

func (x *MigrationPayload_OtpParameters) GetType() MigrationPayload_OtpType {
	if x != nil {
		return x.Type
	}
	return MigrationPayload_OTP_TYPE_UNSPECIFIED
}

func (x *MigrationPayload_OtpParameters) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_migration_proto protoreflect.FileDescriptor

const file_migration_proto_rawDesc = "" +
	"\n" +
	"\x0fmigration.proto\x12\tmigration\"\xdd\x04\n" +
	"\x10MigrationPayload\x12P\n" +
	"\x0eotp_parameters\x18\x01 \x03(\v2).migration.MigrationPayload.OtpParametersR\rotpParameters\x1a\xab\x02\n" +
	"\rOtpParameters\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12C\n" +
	"\talgorithm\x18\x04 \x01(\x0e2%.migration.MigrationPayload.AlgorithmR\talgorithm\x12>\n" +
	"\x06digits\x18\x05 \x01(\x0e2&.migration.MigrationPayload.DigitCountR\x06digits\x127\n" +
	"\x04type\x18\x06 \x01(\x0e2#.migration.MigrationPayload.OtpTypeR\x04type\x12\x18\n" +
	"\acounter\x18\a \x01(\x03R\acounter\"Q\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SHA1\x10\x01\x12\n" +
	"\n" +
	"\x06SHA256\x10\x02\x12\n" +
	"\n" +
	"\x06SHA512\x10\x03\x12\a\n" +
	"\x03MD5\x10\x04\"=\n" +
	"\n" +
	"DigitCount\x12\x1b\n" +
	"\x17DIGIT_COUNT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SIX\x10\x01\x12\t\n" +
	"\x05EIGHT\x10\x02\"7\n" +
	"\aOtpType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HOTP\x10\x01\x12\b\n" +
	"\x04TOTP\x10\x02B>Z<github.com/nktmys/winticator/src/usecase/totpstore/migrationb\x06proto3"

var (
	file_migration_proto_rawDescOnce sync.Once
	file_migration_proto_rawDescData []byte
)

func file_migration_proto_rawDescGZIP() []byte {
	file_migration_proto_rawDescOnce.Do(func() {
		file_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)))
	})
	return file_migration_proto_rawDescData
}

var file_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_migration_proto_goTypes = []any{
	(MigrationPayload_Algorithm)(0),        // 0: migration.MigrationPayload.Algorithm
	(MigrationPayload_DigitCount)(0),       // 1: migration.MigrationPayload.DigitCount
	(MigrationPayload_OtpType)(0),          // 2: migration.MigrationPayload.OtpType
	(*MigrationPayload)(nil),               // 3: migration.MigrationPayload
	(*MigrationPayload_OtpParameters)(nil), // 4: migration.MigrationPayload.OtpParameters
}
var file_migration_proto_depIdxs = []int32{
	4, // 0: migration.MigrationPayload.otp_parameters:type_name -> migration.MigrationPayload.OtpParameters
	0, // 1: migration.MigrationPayload.OtpParameters.algorithm:type_name -> migration.MigrationPayload.Algorithm
	1, // 2: migration.MigrationPayload.OtpParameters.digits:type_name -> migration.MigrationPayload.DigitCount
	2, // 3: migration.MigrationPayload.OtpParameters.type:type_name -> migration.MigrationPayload.OtpType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_migration_proto_init() }
func file_migration_proto_init() {
	if File_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_proto_goTypes,
		DependencyIndexes: file_migration_proto_depIdxs,
		EnumInfos:         file_migration_proto_enumTypes,
		MessageInfos:      file_migration_proto_msgTypes,
	}.Build()
	File_migration_proto = out.File
	file_migration_proto_goTypes = nil
	file_migration_proto_depIdxs = nil
}
