version: '3.9'

services:
  winticator:
    container_name: winticator
    build:
      context: .
    tty: true
    stdin_open: true
    working_dir: /app
    env_file: .env
    environment:
      - XDG_SESSION_TYPE=x11
      - CLAUDE_CONFIG_DIR=/home/develop/.claude
    volumes:
      - ../.cache/claude:/home/develop/.claude
      - ../:/app
